package model.pojo;
// Generated 17/10/2014 10:25:18 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String txtNombreCategoria;
     private boolean intActivo;
     private Set libros = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String txtNombreCategoria, boolean intActivo) {
        this.txtNombreCategoria = txtNombreCategoria;
        this.intActivo = intActivo;
    }
    public Categoria(String txtNombreCategoria, boolean intActivo, Set libros) {
       this.txtNombreCategoria = txtNombreCategoria;
       this.intActivo = intActivo;
       this.libros = libros;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getTxtNombreCategoria() {
        return this.txtNombreCategoria;
    }
    
    public void setTxtNombreCategoria(String txtNombreCategoria) {
        this.txtNombreCategoria = txtNombreCategoria;
    }
    public boolean isIntActivo() {
        return this.intActivo;
    }
    
    public void setIntActivo(boolean intActivo) {
        this.intActivo = intActivo;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }




}


