package model.pojo;
// Generated 17/10/2014 10:25:18 AM by Hibernate Tools 3.6.0



/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private Integer idLibro;
     private Categoria categoria;
     private String txtNombre;
     private String txtAutor;
     private String txtEditorial;
     private String txtIsbn;
     private boolean intActivo;

    public Libro() {
    }

    public Libro(Categoria categoria, String txtNombre, String txtAutor, String txtEditorial, String txtIsbn, boolean intActivo) {
       this.categoria = categoria;
       this.txtNombre = txtNombre;
       this.txtAutor = txtAutor;
       this.txtEditorial = txtEditorial;
       this.txtIsbn = txtIsbn;
       this.intActivo = intActivo;
    }
   
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getTxtNombre() {
        return this.txtNombre;
    }
    
    public void setTxtNombre(String txtNombre) {
        this.txtNombre = txtNombre;
    }
    public String getTxtAutor() {
        return this.txtAutor;
    }
    
    public void setTxtAutor(String txtAutor) {
        this.txtAutor = txtAutor;
    }
    public String getTxtEditorial() {
        return this.txtEditorial;
    }
    
    public void setTxtEditorial(String txtEditorial) {
        this.txtEditorial = txtEditorial;
    }
    public String getTxtIsbn() {
        return this.txtIsbn;
    }
    
    public void setTxtIsbn(String txtIsbn) {
        this.txtIsbn = txtIsbn;
    }
    public boolean isIntActivo() {
        return this.intActivo;
    }
    
    public void setIntActivo(boolean intActivo) {
        this.intActivo = intActivo;
    }




}


