package model.pojo;
// Generated 27/11/2014 11:37:40 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private Integer idConsulta;
     private Paciente paciente;
     private Date fechaConsulta;
     private String txtDescripcion;
     private String estatus;
     private byte activo;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public Consulta() {
    }

    public Consulta(Paciente paciente, Date fechaConsulta, String txtDescripcion, String estatus, byte activo, Date fechaCreacion, Date fechaModificacion) {
       this.paciente = paciente;
       this.fechaConsulta = fechaConsulta;
       this.txtDescripcion = txtDescripcion;
       this.estatus = estatus;
       this.activo = activo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdConsulta() {
        return this.idConsulta;
    }
    
    public void setIdConsulta(Integer idConsulta) {
        this.idConsulta = idConsulta;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFechaConsulta() {
        return this.fechaConsulta;
    }
    
    public void setFechaConsulta(Date fechaConsulta) {
        this.fechaConsulta = fechaConsulta;
    }
    public String getTxtDescripcion() {
        return this.txtDescripcion;
    }
    
    public void setTxtDescripcion(String txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(byte activo) {
        this.activo = activo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


