package model.pojo;
// Generated 27/11/2014 11:37:40 AM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente implements java.io.Serializable {

    private Integer idPaciente;
    private String txtNombre;
    private String txtApellido;
    private String txtTelefono;
    private String txtCelular;
    private String txtDomicilio;
    private String txtEmail;
    private String txtToken;
    private byte activo;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private Set<Consulta> consultas = new HashSet<Consulta>(0);

    public Paciente() {
    }

    public Paciente(String txtNombre, String txtToken, byte activo, Date fechaCreacion, Date fechaModificacion) {
        this.txtNombre = txtNombre;
        this.txtToken = txtToken;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
    }

    /*
    public Paciente(String txtNombre, String txtApellido, String txtTelefono, String txtCelular, String txtDomicilio, String txtEmail, String txtToken, byte activo, Date fechaCreacion, Date fechaModificacion, Set<Consulta> consultas) {
        this.txtNombre = txtNombre;
        this.txtApellido = txtApellido;
        this.txtTelefono = txtTelefono;
        this.txtCelular = txtCelular;
        this.txtDomicilio = txtDomicilio;
        this.txtEmail = txtEmail;
        this.txtToken = txtToken;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.consultas = consultas;
    }*/

    /*Constructor para obtener el listado principal de pacientes*/
    //(idPaciente,txtNombre,txtApellido,txtTelefono,txtCelular,txtEmail
    public Paciente(int idPaciente, String txtNombre, String txtApellido, String txtTelefono, String txtCelular, String txtEmail) {
        this.idPaciente = idPaciente;
        this.txtNombre = txtNombre;
        this.txtApellido = txtApellido;
        this.txtTelefono = txtTelefono;
        this.txtCelular = txtCelular;
        this.txtEmail = txtEmail;
    }

    public Integer getIdPaciente() {
        return this.idPaciente;
    }

    @Override
    public String toString() {
        return "Paciente{" + "idPaciente=" + idPaciente + ", txtNombre=" + txtNombre + ", txtApellido=" + txtApellido + ", txtTelefono=" + txtTelefono + ", txtCelular=" + txtCelular + ", txtDomicilio=" + txtDomicilio + ", txtEmail=" + txtEmail + ", txtToken=" + txtToken + ", activo=" + activo + ", fechaCreacion=" + fechaCreacion + ", fechaModificacion=" + fechaModificacion + ", consultas=" + consultas + '}';
    }

    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    public String getTxtNombre() {
        return this.txtNombre;
    }

    public void setTxtNombre(String txtNombre) {
        this.txtNombre = txtNombre;
    }

    public String getTxtApellido() {
        return this.txtApellido;
    }

    public void setTxtApellido(String txtApellido) {
        this.txtApellido = txtApellido;
    }

    public String getTxtTelefono() {
        return this.txtTelefono;
    }

    public void setTxtTelefono(String txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public String getTxtCelular() {
        return this.txtCelular;
    }

    public void setTxtCelular(String txtCelular) {
        this.txtCelular = txtCelular;
    }

    public String getTxtDomicilio() {
        return this.txtDomicilio;
    }

    public void setTxtDomicilio(String txtDomicilio) {
        this.txtDomicilio = txtDomicilio;
    }

    public String getTxtEmail() {
        return this.txtEmail;
    }

    public void setTxtEmail(String txtEmail) {
        this.txtEmail = txtEmail;
    }

    public String getTxtToken() {
        return this.txtToken;
    }

    public void setTxtToken(String txtToken) {
        this.txtToken = txtToken;
    }

    public byte getActivo() {
        return this.activo;
    }

    public void setActivo(byte activo) {
        this.activo = activo;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public Set<Consulta> getConsultas() {
        return this.consultas;
    }

    public void setConsultas(Set<Consulta> consultas) {
        this.consultas = consultas;
    }

}
